apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
  labels:
    app: portal
spec:
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: portal:latest
          ports:
            - containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: portal-service
  labels:
    app: portal
spec:
  selector:
      app: portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080